// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("NTiled")]
[assembly: AssemblyVersionAttribute("0.1.7")]
[assembly: AssemblyFileVersionAttribute("0.1.7")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Patrik Svensson 2014")]
